// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestao_de_frotasAPI.Models;

public partial class ENDERECO
{
    public int ID { get; set; }

    public int? ID_USUARIO { get; set; }

    public string LOGRADOURO { get; set; }

    public string BAIRRO { get; set; }

    public string CIDADE { get; set; }

    public string ESTADO { get; set; }

    public int? NUMERO { get; set; }

    public virtual USUARIO ID_USUARIONavigation { get; set; }
}