// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestao_de_frotasAPI.Models;

public partial class GASTO
{
    public int ID { get; set; }

    public int ID_VIAGEM { get; set; }

    public int? TP_GASTO { get; set; }

    public int? DT_GASTO { get; set; }

    public string ESTABELECIMENTO { get; set; }

    public double? VALOR_UNITARIO { get; set; }

    public double? VALOR_TOTAL { get; set; }

    public int? QUANTIDADE { get; set; }

    public virtual VIAGEM ID_VIAGEMNavigation { get; set; }
}