// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestao_de_frotasAPI.Models;

public partial class MANUTENCO
{
    public int ID { get; set; }

    public int? ID_VEICULO { get; set; }

    public DateOnly? DT_MANUTENCAO { get; set; }

    public string FORNECEDOR { get; set; }

    public string TP_MANUTENCAO { get; set; }

    public double? VALOR { get; set; }

    public string DESCRICAO { get; set; }

    public string PECAS_TROCADAS { get; set; }

    public virtual VEICULO ID_VEICULONavigation { get; set; }
}