// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestao_de_frotasAPI.Models;

public partial class Multa
{
    public int ID { get; set; }

    public int? ID_VEICULO { get; set; }

    public int? ID_VIAGEM { get; set; }

    public DateOnly? DT_MULTA { get; set; }

    public string TP_INFRACAO { get; set; }

    public double? VALOR { get; set; }

    public int? PTS_CARTEIRA { get; set; }

    public string DESCRICAO { get; set; }

    public virtual VEICULO ID_VEICULONavigation { get; set; }

    public virtual VIAGEM ID_VIAGEMNavigation { get; set; }
}