// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestao_de_frotasAPI.Models;

public partial class USUARIO
{
    public int ID { get; set; }

    public string PRIMEIRO_NOME { get; set; }

    public string SOBRENOME { get; set; }

    public string EMAIL { get; set; }

    public string CARGO { get; set; }

    public int? CPF { get; set; }

    public int? CNH { get; set; }

    public string TIPO_CNH { get; set; }

    public DateOnly? DT_NASCIMENTO { get; set; }

    public virtual ICollection<ENDERECO> ENDERECOs { get; set; } = new List<ENDERECO>();

    public virtual ICollection<VIAGEM> VIAGEMs { get; set; } = new List<VIAGEM>();
}