// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestao_de_frotasAPI.Models;

public partial class VEICULO
{
    public int ID { get; set; }

    public string MARCA { get; set; }

    public string MODELO { get; set; }

    public int? ANO { get; set; }

    public string PLACA { get; set; }

    public int? QUILOMETRAGEM { get; set; }

    public string TP_COMBUSTIVEL { get; set; }

    public DateOnly? DT_AQUISICAO { get; set; }

    public string STATUS { get; set; }

    public virtual ICollection<MANUTENCO> MANUTENCOs { get; set; } = new List<MANUTENCO>();

    public virtual ICollection<Multa> MULTa { get; set; } = new List<Multa>();

    public virtual ICollection<VIAGEM> VIAGEMs { get; set; } = new List<VIAGEM>();
}