// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestao_de_frotasAPI.Models;

public partial class VIAGEM
{
    public int ID { get; set; }

    public int ID_MOTORISTA { get; set; }

    public int ID_VEICULO { get; set; }

    public DateOnly? DT_INICIO { get; set; }

    public DateOnly? DT_FIM { get; set; }

    public string ORIGEM { get; set; }

    public string DESTINO { get; set; }

    public string STATUS { get; set; }

    public int? KM_INICIAL { get; set; }

    public int? KM_FINAL { get; set; }

    public virtual ICollection<GASTO> GASTOs { get; set; } = new List<GASTO>();

    public virtual USUARIO ID_MOTORISTANavigation { get; set; }

    public virtual VEICULO ID_VEICULONavigation { get; set; }

    public virtual ICollection<Multa> MULTa { get; set; } = new List<Multa>();
}